"""
services/planner_service.py

Top-level orchestration:

  fetch_emails()
      ↓ (concurrent fan-out)
  groq_service.extract_events_from_email()    ← per email
      ↓
  priority_engine.rank_events_async()         ← concurrent Groq company calls
      ↓
  groq_service.generate_daily_plan()
      ↓
  firebase_service.save_*()                   ← persist events + plan
      ↓
  return GeneratePlanResponse
"""
from __future__ import annotations

import asyncio
import json
import logging
from typing import List, Optional

from models.schemas import (
    DailyPlan,
    ExtractedEvent,
    GeneratePlanResponse,
    HourlyBlock,
    ScoredEvent,
    StudentProfile,
)
from services import firebase_service, gmail_service, groq_service
from services.priority_engine import rank_events_async
from utils.date_utils import now_iso, today_utc

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Fallback plan (when Groq is unavailable)
# ─────────────────────────────────────────────────────────────────────────────

def _fallback_plan(sorted_events: List[ScoredEvent]) -> DailyPlan:
    if not sorted_events:
        return DailyPlan(
            focus_verdict="Free day — no urgent events detected.",
            reason="No placement or academic events found in recent emails.",
            hourly_breakdown=[
                HourlyBlock(hours=2, task="Revise core CS fundamentals", reason="Always useful."),
                HourlyBlock(hours=1, task="Solve 3 LeetCode Medium problems", reason="Daily coding habit."),
            ],
            skip_today=[],
            warning="",
        )

    top = sorted_events[0]
    breakdown: List[HourlyBlock] = []
    allocated = 0.0

    for event in sorted_events[:4]:
        hours = 3.0 if (event.days_until is not None and event.days_until <= 1) else 2.0
        if allocated + hours > 9:
            hours = max(9.0 - allocated, 0.5)
        tier_label = ""
        if event.company_profile:
            tier_label = f" [{event.company_profile.tier.value}]"
        is_critical = event.days_until is not None and event.days_until <= 1
        days_str = "⚠ CRITICAL: today/tomorrow!" if is_critical else f"in {event.days_until or '?'} day(s)."
        breakdown.append(
            HourlyBlock(
                hours=hours,
                task=f"Prepare: {event.title}{tier_label}",
                reason=f"Score {event.priority_score:.2f} — {days_str}",
            )
        )
        allocated += hours
        if allocated >= 9:
            break

    days_label = f"in {top.days_until} day(s)" if top.days_until is not None else "soon"
    return DailyPlan(
        focus_verdict=top.title,
        reason=f"Highest priority score ({top.priority_score:.2f}) — {days_label}.",
        hourly_breakdown=breakdown,
        skip_today=[e.title for e in sorted_events[4:]],
        warning="Groq API unavailable — plan generated by deterministic fallback engine.",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Event extraction (concurrent fan-out)
# ─────────────────────────────────────────────────────────────────────────────

async def _extract_events_from_emails(
    google_access_token: Optional[str] = None,
) -> List[ExtractedEvent]:
    emails = await gmail_service.fetch_emails(google_access_token=google_access_token)
    logger.info("Fetched %d emails.", len(emails))

    extraction_tasks = [
        groq_service.extract_events_from_email(e.subject, e.body)
        for e in emails
    ]
    results: list[list[dict]] = await asyncio.gather(*extraction_tasks)

    events: List[ExtractedEvent] = []
    for email, raw_events in zip(emails, results):
        for raw in raw_events:
            if not isinstance(raw, dict):
                continue
            try:
                # Only pass known ExtractedEvent fields — future-proof against unexpected keys
                allowed_keys = set(ExtractedEvent.model_fields.keys())
                filtered = {k: v for k, v in raw.items() if k in allowed_keys}
                event = ExtractedEvent(source_email_id=email.id, **filtered)
                events.append(event)
            except Exception as exc:
                logger.warning(
                    "Skipping malformed event from email '%s': %s — %s",
                    email.id, raw, exc,
                )

    logger.info("Extracted %d valid events total.", len(events))
    return events


# ─────────────────────────────────────────────────────────────────────────────
# Plan generation (Token Optimisation)
# ─────────────────────────────────────────────────────────────────────────────

def _prepare_events_for_llm_plan(events: List[ScoredEvent]) -> str:
    """
    Strip ScoredEvent objects down to the bare minimum needed for planning.
    Saves 50-70% tokens compared to full model_dump().
    """
    minimal = []
    for e in events:
        minimal.append({
            "title": e.title,
            "type": e.event_type.value,
            "priority": round(e.priority_score, 1),
            "days_until": e.days_until,
            "company": e.company_profile.normalized_name if e.company_profile else None
        })
    return json.dumps(minimal, indent=2)


async def _build_plan_from_groq(sorted_events: List[ScoredEvent]) -> Optional[DailyPlan]:
    payload = _prepare_events_for_llm_plan(sorted_events)
    logger.debug("Plan generation payload size: %d chars", len(payload))
    raw = await groq_service.generate_daily_plan(payload)
    if not raw:
        return None
    try:
        # Coerce hourly_breakdown dicts into HourlyBlock objects
        raw["hourly_breakdown"] = [
            HourlyBlock(**block) if isinstance(block, dict) else block
            for block in raw.get("hourly_breakdown", [])
        ]
        return DailyPlan(**raw)
    except Exception as exc:
        logger.warning("Groq plan failed Pydantic validation: %s", exc)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Main entry-point
# ─────────────────────────────────────────────────────────────────────────────

async def generate_plan(
    user_id: str = "anonymous",
    google_access_token: Optional[str] = None,
) -> GeneratePlanResponse:
    """
    Full pipeline:
      1. Fetch emails — uses the Google access token from Firebase Auth popup;
         falls back to dynamic mock corpus when token is absent.
      2. Extract events via Groq (concurrent per email)
      3. Load student profile + today's study hours from Firebase (concurrent)
      4. Score & rank events (concurrent Groq company classification)
      5. Generate daily plan via Groq (with deterministic fallback)
      6. Persist events + plan to Firebase
      7. Return GeneratePlanResponse
    """
    today_str = today_utc().isoformat()

    # Step 1–2: email extraction — forward the Firebase Google access token
    events_task = asyncio.create_task(
        _extract_events_from_emails(google_access_token=google_access_token)
    )

    # Step 3: Firebase reads (fast, run concurrently with extraction)
    profile_task = asyncio.create_task(firebase_service.get_student_profile(user_id))
    study_task   = asyncio.create_task(firebase_service.get_today_study_hours(user_id, today_str))

    events, raw_profile, hours_studied = await asyncio.gather(
        events_task, profile_task, study_task
    )

    student_profile: Optional[StudentProfile] = None
    if raw_profile:
        try:
            student_profile = StudentProfile(user_id=user_id, **raw_profile)
        except Exception as exc:
            logger.warning("Could not parse student profile: %s", exc)

    logger.info(
        "User '%s' | studied=%.2fh | events=%d | profile=%s",
        user_id, hours_studied, len(events),
        "loaded" if student_profile else "not found",
    )

    # Step 4: rank (concurrent Groq company calls inside rank_events_async)
    sorted_events = await rank_events_async(events, hours_studied, student_profile)

    # Step 5: plan
    daily_plan = await _build_plan_from_groq(sorted_events)
    if daily_plan is None:
        logger.warning("Falling back to rule-based plan generator.")
        daily_plan = _fallback_plan(sorted_events)

    # Step 6: persist concurrently (fire-and-forget failures don't block response)
    serialised_events = [e.model_dump() for e in sorted_events]
    serialised_plan   = daily_plan.model_dump()
    await asyncio.gather(
        firebase_service.save_scored_events(user_id, today_str, serialised_events),
        firebase_service.save_daily_plan(user_id, today_str, serialised_plan),
        return_exceptions=True,   # persistence failures are non-fatal
    )

    return GeneratePlanResponse(
        sorted_events=sorted_events,
        daily_plan=daily_plan,
        generated_at=now_iso(),
    )
